# Generated by Django 4.0.3 on 2022-06-04 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherdata',
            name='department',
            field=models.CharField(max_length=50),
        ),
    ]
