# Generated by Django 4.0.3 on 2022-06-04 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_alter_teacherdata_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherdata',
            name='collegeid',
            field=models.CharField(default='MCKVIE_ID_IS_TRUE', max_length=30, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacherdata',
            name='firstname',
            field=models.CharField(max_length=50),
        ),
    ]
