# Generated by Django 4.0.3 on 2022-06-06 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_agtest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgTest',
        ),
    ]
