# Generated by Django 4.0.3 on 2022-07-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_delete_agtest'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherdata',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
